### ISSUE TITLE
Error with deprication

### ISSUE THREAD

**Issue by mohfullstack** [mrkem598/egen-fe-challenge#1]
Hello Mohammed I have been trying to play with your code and I have come up with an error saying the "angular-cli" has been deprecated how may I resolve this , can you please help me out i really appreciate that.

**Comment by mohfullstack** [comment]
<img width="918" alt="screen shot 2017-08-11 at 5 11 05 pm" src="https://user-images.githubusercontent.com/30382246/29232173-3fbe6748-7eb8-11e7-8dfe-b92d373636c8.png">

**Comment by mohfullstack** [comment]
here is the error snipet

**Comment by mrkem598** [comment]
hello @mohfullstack if you uninstall angular-cli first and re install globally in your terminal. 
 "npm uninstall --save-dev  @angular/cli" 
  "npm install --save-dev  @angular/cli/latest"
will resolve your error. Let me know if it works or not!
